---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogImMzUmtMVEF4TXkweU1EbzJkVEpVTTJjelRBPT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson

---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    app: "{{ .Chart.Name }}"
type: Opaque
data:
  DB: bW9uZ29kYjovL3N0ZC0wMTMtMjA6UCU0MHNzdzByZEByYzFhLXhiNnE3cG13MzZ0NzdyeXoubWRiLnlhbmRleGNsb3VkLm5ldDoyNzAxOC9zdGQtMDEzLTIwP3Rscz10cnVlJnRsc0NhRmlsZT1ZYW5kZXhJbnRlcm5hbFJvb3RDQS5jcnQ=